# also see https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: CI

on:
    push:
        branches: ['develop', 'master', 'feature/deploy_setup']
        tags: ['v*']
    pull_request: 
        branches: [master']

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest
        # Configuring builder 
        # https://docs.docker.com/build/ci/github-actions/configure-builder/
        # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio
        steps:
            - name: Checkout
              # https://github.com/actions/checkout
              uses: actions/checkout@v3

            - name: Extract metadata (tags, labels) for Docker
              # https://github.com/docker/metadata-action
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
              with:
                buildkitd-flags: --debug

            # https://github.com/docker/login-action#github-container-registry
            - name: Login into registry ${{ env.REGISTRY }}
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v2
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
            