# also see https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: CI

on:
    push:
        branches: ['develop', 'master', 'feature/deploy_setup']
    pull_request: 
        branches: ['develop']
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3


            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
              with:
                buildkitd-flags: --debug
            
            - name: Build
              uses: docker/build-push-action@v4
              with:
                context: .
               
            